"""Markdown and migration renderers."""

from __future__ import annotations

from pathlib import Path

from cobol_agent.models import CobolProgram, IndexResult


class MarkdownRenderer:
    """Render index data into Markdown documentation."""

    def render_summary(self, index: IndexResult) -> str:
        lines = [
            f"# COBOL Repository Summary: {index.repo_path.name}",
            "",
            f"- Source files: {index.program_count}",
            f"- Copybooks: {index.copybook_count}",
            f"- JCL files: {index.jcl_count}",
            "",
            "## Programs",
            "",
        ]
        if not index.programs:
            lines.append("No COBOL sources were found.")
        for program in index.programs:
            lines.extend(self._program_summary_lines(program))
            lines.append("")
        return "\n".join(lines).rstrip() + "\n"

    def render_program_doc(self, program: CobolProgram, root: Path) -> str:
        rel_path = self._relative(program.path, root)
        lines = [
            f"# {program.name}",
            "",
            f"- Path: `{rel_path}`",
            f"- Type: `{program.source_type}`",
            f"- Lines: {program.lines}",
            "",
            "## Structure",
            "",
            f"- Divisions: {self._csv(program.divisions)}",
            f"- Sections: {self._csv(program.sections)}",
            f"- Paragraphs: {self._csv(program.paragraphs)}",
            "",
            "## Dependencies",
            "",
            f"- Copybooks: {self._csv(program.copybooks)}",
            f"- Calls: {self._csv(program.calls)}",
            f"- Files: {self._csv(program.file_declarations)}",
            f"- SQL blocks: {len(program.sql_blocks)}",
        ]
        return "\n".join(lines).rstrip() + "\n"

    def _program_summary_lines(self, program: CobolProgram) -> list[str]:
        return [
            f"### {program.name}",
            "",
            f"- Type: `{program.source_type}`",
            f"- Lines: {program.lines}",
            f"- Divisions: {self._csv(program.divisions)}",
            f"- Copybooks: {self._csv(program.copybooks)}",
            f"- Calls: {self._csv(program.calls)}",
        ]

    def _csv(self, values: list[str]) -> str:
        return ", ".join(values) if values else "None detected"

    def _relative(self, path: Path, root: Path) -> str:
        try:
            return str(path.relative_to(root))
        except ValueError:
            return str(path)


class PythonMigrationRenderer:
    """Generate scaffolded Python migration output from parsed COBOL facts."""

    def render_module(self, program: CobolProgram) -> str:
        class_name = self._python_identifier(program.name, title=True)
        function_name = self._python_identifier(program.name)
        lines = [
            '"""Generated Python migration scaffold from COBOL Agent.',
            "",
            "Review business rules, file IO, SQL access, and numeric precision "
            "before production use.",
            '"""',
            "",
            "from dataclasses import dataclass",
            "",
            "",
            "@dataclass",
            f"class {class_name}Context:",
            '    """Runtime state translated from COBOL working storage."""',
            "",
            "    raw_record: str | None = None",
            "",
            "",
            f"def {function_name}(context: {class_name}Context) -> None:",
            f'    """Migrated entrypoint for {program.name}."""',
            "    # TODO: Translate COBOL paragraphs into Python business logic.",
        ]
        for paragraph in program.paragraphs[:20]:
            lines.append(f"    # COBOL paragraph detected: {paragraph}")
        if program.calls:
            lines.append(f"    # External calls: {', '.join(program.calls)}")
        if program.copybooks:
            lines.append(f"    # Copybooks: {', '.join(program.copybooks)}")
        if program.sql_blocks:
            lines.append(f"    # SQL blocks detected: {len(program.sql_blocks)}")
        lines.append("    raise NotImplementedError('Manual migration required')")
        return "\n".join(lines) + "\n"

    def render_report(self, index: IndexResult, generated_files: list[Path]) -> str:
        lines = [
            f"# COBOL to Python Migration Report: {index.repo_path.name}",
            "",
            "This report lists scaffolded migration files generated by COBOL Agent.",
            "Generated code is intentionally conservative and requires review.",
            "",
            "## Generated Files",
            "",
        ]
        for path in generated_files:
            lines.append(f"- `{path.name}`")
        lines.extend(
            [
                "",
                "## Source Inventory",
                "",
                f"- Source files: {index.program_count}",
                f"- Copybooks: {index.copybook_count}",
                f"- JCL files: {index.jcl_count}",
            ]
        )
        return "\n".join(lines).rstrip() + "\n"

    def module_filename(self, program: CobolProgram) -> str:
        return f"{self._python_identifier(program.name)}.py"

    def _python_identifier(self, value: str, title: bool = False) -> str:
        parts = [part for part in re_split_identifier(value) if part]
        if not parts:
            return "migrated_program" if not title else "MigratedProgram"
        if title:
            return "".join(part.capitalize() for part in parts)
        return "_".join(part.lower() for part in parts)


def re_split_identifier(value: str) -> list[str]:
    import re

    return re.split(r"[^A-Za-z0-9]+", value)
